// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleLogIn.Data;

#nullable disable

namespace SimpleLogIn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230807173113_dbcreated")]
    partial class dbcreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("SimpleLogIn.Models.EmailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            UserEmail = "kadwales@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Password = "12365657",
                            UserEmail = "wales@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
